
name = "DashCoreComponents"
uuid = "1b08a953-4be3-4667-9a23-03c9473d1193"
authors = ["Chris Parmer <chris@plot.ly>"]
version = "1.4.0"

[deps]
DashBase = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"

[compact]
julia = "1.2"
DashBase = ">=0.1"
